[sources]
new_data_source = "localhost:8001/new"
# this is kinda weird; the viewset that uses this endpoint supplies a value for the endpoint parameter, so it has to be truncated like this
bulk_data_source = "http://localhost:8001/bulk?samples="

[database]
host = "73.248.135.215"
database = "sweng"
user = "USER"
password = "PASSWORD"