[data_sources]
new_sample = "http://localhost:8001/new"
# this is kinda weird; the viewset that uses this endpoint supplies a value for the endpoint parameter, so it has to be truncated like this
bulk_samples = "http://localhost:8001/bulk?samples="

[database]
database = "sweng"
user = ""
password = ""
host = ""

[auth]
bearer = "4c5b35f9f82fd394d135fe6b40a33c3ec756e384"