[data_sources]
new_sample = "http://dummy/new"
# this is kinda weird; the viewset that uses this endpoint supplies a value for the endpoint parameter, so it has to be truncated like this
bulk_samples = "http://dummy/bulk?samples="

[database]
database = "sweng"
user = ""
password = ""
host = ""

[auth]
bearer = ""

[email]
sender = "wpvprediction@gmail.com"
password = ""
recipients = [""]