services:
  wpv:
    image: wpv-api
    container_name: wpv-api
    build: .
    command: daphne -b 0.0.0.0 -p 8000 WorkplaceViolencePredictionAPI.asgi:application
    ports:
      - "8000:8000"

  dummy:
    image: dummy-api
    container_name: dummy-api
    build: https://git.bobbitt.dev/avery/dummy-system-api.git
    ports:
      - "8001:80"