services:
  wpv:
    image: wpv-api
    container_name: wpv-api
    build: .
    command: daphne WorkplaceViolencePredictionAPI.asgi:application -b 0.0.0.0
    ports:
      - "8000:8000"

  dummy:
    image: abobbitt/sweng-dummy-api
    container_name: dummy-api
    ports:
      - "8001:80"