openapi: 3.0.0
info:
  title: Hospital Data API
  version: 0.1.0
  description: API for predicting workplace violence using a Random Forest machine learning model

servers:
  - url: localhost

paths:
  /api/hello/world:
    get:
      summary: Get hello world message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/hello/admin:
    get:
      summary: Get hello admin message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/token:
    get:
      summary: Get authentication token
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
        '401':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
    post:
      summary: Create a new authentication token
      responses:
        '201':
          description: Token created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
  /api/data:
    get:
      summary: Get hospital data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalData'
    post:
      summary: Create hospital data entry
      responses:
        '201':
          description: Hospital data entry created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalData'
  /api/data/latest:
    get:
      summary: Get latest hospital data entry
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalData'
      security:
        - bearerAuth: [ ]
  /api/train:
  /api/model:
    get:
      summary: Query the prediction model for a prediction
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
  /api/log:
  /api/email:


components:
  schemas:
    HospitalData:
      type: object
      properties:
        id:
          type: integer
        createdTime:
          type: string
          format: date-time
        avgNurses:
          type: number
          format: decimal
        avgPatients:
          type: number
          format: decimal
        percentBedsFull:
          type: number
          format: decimal
        timeOfDay:
          type: string
          format: time
    TrainingData:
      type: object
      properties:
        id:
          type: integer
        createdTime:
          type: string
          format: date-time
        avgNurses:
          type: number
          format: decimal
        avgPatients:
          type: number
          format: decimal
        percentBedsFull:
          type: number
          format: decimal
        timeOfDay:
          type: string
          format: time
        wpvRisk:
          type: boolean
    RiskData:
      type: object
      properties:
        id:
          type: integer
        hData:
          type: integer
        wpvRisk:
          type: boolean
        wpvProbability:
          type: number
          format: decimal
    IncidentLog:
      type: object
      properties:
        id:
          type: integer
        inidentType:
          type: string
        incidentDate:
          type: string
          format: date-time
        affectedPeople:
          type: string
        incidentDescription:
          type: string
        hData:
          type: integer

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BasicAuth: [ ]
  - BearerAuth: [ ]
